// Public API exports for Hypervigilant

export {
  type AgentDeliveryOptions,
  type BatchDeliveryResult,
  createApprovalCallback,
  type DeliveryResult,
  deliverBatch,
  EDIT_TOOLS,
  hasUnresolvedApproval,
  MUTATING_TOOLS,
  READ_ONLY_TOOLS,
  REVIEW_TOOLS,
  resolveConversationId,
  TurnSerializer,
  updateConversationState,
} from "./agent.ts";
export { renderDiffPreview, renderDiffPreviews } from "./approval-diff.ts";
export { resolveCloudApiKey } from "./auth.ts";
export {
  type Batcher,
  type BatcherOptions,
  collapseChanges,
  createBatcher,
  DebounceBatcher,
  FixedWindowBatcher,
  type FlushCallback,
  ImmediateBatcher,
} from "./batcher.ts";
export {
  type ClientToolsConfig,
  type ConfiguredClientToolPolicy,
  configuredClientToolNames,
  configuredClientToolPolicy,
  LOCAL_MUTATION_TOOLS,
  LOCAL_READ_TOOLS,
  PROHIBITED_LOCAL_TOOLS,
  RESERVED_LOCAL_TOOLS,
} from "./client-tools.ts";
export {
  AGENT_MODES,
  type AgentMode,
  BATCHING_STRATEGIES,
  type BatchingStrategy,
  type ClientTools,
  CONFIG_FILENAME,
  CONVERSATION_ROUTING,
  type ConfigParseResult,
  type ConversationRouting,
  configSchema,
  createGlobMatcher,
  DEFAULT_STATE_DIR,
  type GlobMatcher,
  type HypervigilantConfig,
  LEGACY_CONFIG_FILENAME,
  loadConfig,
  PROMPT_RULE_EVENTS,
  type PromptRule,
  type PromptRuleEvent,
  type ResolvedConfigPath,
  resolveConfigPath,
  STATE_FILENAME,
  serializeConfigToml,
  validateConfig,
} from "./config.ts";
export {
  type FileChange as DiffFileChange,
  formatDiffMessage,
  renderBatchDiff,
  renderDiff,
} from "./diff.ts";
export {
  type InitDependencies,
  type InitOptions,
  type InitResult,
  initCommand,
} from "./init.ts";
export {
  configuredPermissionPolicy,
  getPermissionStatus,
  PERMISSION_POLICIES,
  type PermissionPolicy,
  type PermissionState,
  type PermissionStatus,
  permissionAgentMode,
  permissionStatePath,
  resetPermissionPolicy,
  setPermissionPolicy,
} from "./permissions.ts";
export {
  formatPromptRuleSection,
  type MatchedPromptRule,
  matchPromptRules,
  type PromptChange,
  toPromptRuleEvent,
} from "./prompts.ts";
export {
  atomicWriteFile,
  atomicWriteJSON,
  type FileKind,
  type FileSnapshot,
  getFileConversationId,
  getNamedConversationId,
  type HypervigilantState,
  hashBytes,
  hashContent,
  removeSnapshot,
  resetConversationRoutes,
  StateStore,
  setFileConversation,
  setNamedConversation,
  setProjectConversation,
  setSnapshot,
  stateSchema,
  toRelPath,
  toSafeRelPath,
} from "./state.ts";
export {
  approvalForPolicy,
  establishBaseline,
  establishBinaryBaseline,
  formatDeliveryStatus,
  type WatchOptions,
  watchCommand,
} from "./watch.ts";
export {
  checkFileSize,
  detectOfflineChanges,
  type FileChange,
  type FileChangeCallback,
  FileWatcher,
  type InspectedFile,
  inspectFile,
  isTextFile,
  readFileContent,
  type WatchEvent,
  type WatcherOptions,
  walkProject,
} from "./watcher.ts";
export {
  acquireWorktreeWatcherLock,
  cleanupIsolatedWorktree,
  commitWorktreeBatch,
  getWorktreeStatus,
  mergeIsolatedWorktree,
  prepareAndLockIsolatedWorktree,
  prepareIsolatedWorktree,
  type WorktreeCleanupResult,
  type WorktreeCommit,
  type WorktreeContext,
  type WorktreeMergeResult,
  type WorktreeMetadata,
  type WorktreeStatus,
} from "./worktree.ts";
